[package]
name = "client"
version = "0.1.0"
edition = "2024"

[dependencies]
encryption = { path = "../encryption" }
tokio.workspace = true
tun.workspace = true
etherparse.workspace = true
rand.workspace = true
anyhow.workspace = true
env_logger.workspace = true
log.workspace = true
