[package]
name = "encryption"
version = "0.1.0"
edition = "2024"

[dev-dependencies]
rand.workspace = true

[dependencies]
tokio.workspace = true
anyhow.workspace = true
ringbuf.workspace = true
aead = "0.5.2"
chacha20poly1305 = "0.10.1"
